import type { Metadata } from 'next';
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"
import Footer from "@/components/footer" // Pastikan path-nya benar
import ScrollToTop from '@/components/ScrollToTop'; // Tambahkan baris ini

import 'remixicon/fonts/remixicon.css'

const fontPoppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "CV Habibah | tailwind & next.js",
  description: "Generated by Binti Habibatus Saniyah",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={`${fontPoppins.className} antialiased flex flex-col min-h-screen`} id="About">
        <ScrollToTop />
        <Navbar />
        <main className="grow container mx-auto px-4">
          {children}
        </main>
        <Footer /> {/* Gunakan komponen Footer yang diimpor */}
      </body>
    </html>
  );
}